// ==================== BOOKS DATA - ENHANCED FOR E-BOOKS ====================
const booksData = [
    {
        id: 1,
        title: "உலக தத்துவஞானிகள் சொன்ன ஒரே உண்மை",
        author: "ஆதியும் அந்தமும்",
        price: 449,
        originalPrice: 699,
        category: "philosophy",
        rating: 4.6,
        reviews: 67,
        image: "https://picsum.photos/400/300?random=4",
        description: "புத்தர், சாக்ரடீஸ், காந்தி உள்ளிட்ட உலக தத்துவஞானிகள் சொன்ன ஒரே உண்மை. ஆழமான தத்துவ விளக்கங்களுடன்...",
        badge: "Limited",
        isEbook: true,
        pages: 320,
        fileSize: "2.5 MB",
        format: "PDF",
        samplePages: 5,
        preview: true
    },
    {
        id: 2,
        title: "திருக்குறள் - பொருட்பால் விளக்கம்",
        author: "திருவள்ளுவர்",
        price: 249,
        originalPrice: 399,
        category: "thirukural",
        rating: 4.8,
        reviews: 92,
        image: "https://picsum.photos/400/300?random=5",
        description: "திருக்குறள் பொருட்பாலின் முழுமையான விளக்கம். அரசியல், பொருளாதாரம், நட்பு, குடும்பம் பற்றிய 700 குறள்களின் விளக்கம்.",
        badge: "புதியது",
        isEbook: true,
        pages: 280,
        fileSize: "1.8 MB",
        format: "PDF",
        samplePages: 3,
        preview: true
    },
    {
        id: 3,
        title: "சித்தர்களின் மூச்சுப் பயிற்சிகள்",
        author: "அகத்தியர்",
        price: 349,
        originalPrice: 549,
        category: "siddhar",
        rating: 4.9,
        reviews: 178,
        image: "https://picsum.photos/400/300?random=6",
        description: "சித்தர்களின் மூச்சுப் பயிற்சிகள், பிராணாயாமம் மற்றும் தியான முறைகள். 21 நாள் பயிற்சி மூலம் மன அமைதி அடையுங்கள்.",
        badge: "Bestseller",
        isEbook: true,
        pages: 210,
        fileSize: "1.5 MB",
        format: "PDF",
        samplePages: 4,
        preview: true
    },
    {
        id: 4,
        title: "திருக்குறள் - அறத்துப்பால்",
        author: "திருவள்ளுவர்",
        price: 299,
        originalPrice: 499,
        category: "thirukural",
        rating: 4.8,
        reviews: 124,
        image: "https://picsum.photos/400/300?random=1",
        description: "திருக்குறளின் ஆழமான விளக்கங்களுடன் கூடிய முழுமையான நூல். ஒவ்வொரு குறளுக்கும் விரிவான விளக்கம்.",
        badge: "Bestseller",
        isEbook: true,
        pages: 350,
        fileSize: "2.2 MB",
        format: "PDF",
        samplePages: 5,
        preview: true
    },
    {
        id: 5,
        title: "சித்தர்களின் மன ஆற்றல் ரகசியங்கள்",
        author: "பட்டினத்தார்",
        price: 399,
        originalPrice: 599,
        category: "siddhar",
        rating: 4.9,
        reviews: 89,
        image: "https://picsum.photos/400/300?random=2",
        description: "தமிழ்ச் சித்தர்கள் கூறிய மன ஆற்றல், தியானம் மற்றும் உடல் நல ரகசியங்கள். 18 சித்தர்களின் வாழ்க்கை வரலாறு மற்றும் அவர்களின் போதனைகள்.",
        badge: "New",
        isEbook: true,
        pages: 290,
        fileSize: "2.0 MB",
        format: "PDF",
        samplePages: 4,
        preview: true
    },
    {
        id: 6,
        title: "வாழ்க்கை ஒரு பயணம் - தத்துவக் கதைகள்",
        author: "ஆதியும் அந்தமும்",
        price: 199,
        originalPrice: 299,
        category: "stories",
        rating: 4.7,
        reviews: 156,
        image: "https://picsum.photos/400/300?random=3",
        description: "வாழ்க்கையின் ஆழமான உண்மைகளை எளிய கதைகள் மூலம் விளக்கும் 108 சிறுகதைகள். ஒவ்வொரு கதையும் புதிய பார்வையைத் தரும்.",
        badge: "Popular",
        isEbook: true,
        pages: 180,
        fileSize: "1.2 MB",
        format: "PDF",
        samplePages: 3,
        preview: true
    },
    {
        id: 7,
        title: "மன அமைதிக்கான 108 வழிகள்",
        author: "ஆதியும் அந்தமும்",
        price: 179,
        originalPrice: 249,
        category: "philosophy",
        rating: 4.7,
        reviews: 203,
        image: "https://picsum.photos/400/300?random=7",
        description: "மன அழுத்தம், பயம், கவலைகளிலிருந்து விடுபட்டு மன அமைதி அடைய 108 எளிய வழிகள். தினசரி பயன்பாட்டிற்கான நடைமுறை ஆலோசனைகள்.",
        badge: "Popular",
        isEbook: true,
        pages: 150,
        fileSize: "1.0 MB",
        format: "PDF",
        samplePages: 3,
        preview: true
    },
    {
        id: 8,
        title: "சிறுகதைகள் - ஞானத்தின் சுவடுகள்",
        author: "ஆதியும் அந்தமும்",
        price: 149,
        originalPrice: 199,
        category: "stories",
        rating: 4.8,
        reviews: 145,
        image: "https://picsum.photos/400/300?random=8",
        description: "வாழ்க்கையின் ஆழமான உண்மைகளை உணர்த்தும் 50 சிறுகதைகள். ஒவ்வொரு கதையும் படிக்கப் படிக்க புதிய அர்த்தத்தைத் தரும்.",
        badge: "Offer",
        isEbook: true,
        pages: 130,
        fileSize: "0.9 MB",
        format: "PDF",
        samplePages: 2,
        preview: true
    }
];